import { Task } from "../types/task";

export const initialTasks: Task[] = [
  {
    id: 1,
    title: "Test the system",
    description: "Check application stability",
    category: "Test",
    status: "To Do",
    priority: "Medium",
    createdAt: "2024-07-01T10:00:00.000Z",
  },
  {
    id: 2,
    title: "Update documentation",
    category: "Documentation",
    status: "In Progress",
    priority: "Low",
    createdAt: "2024-07-02T12:30:00.000Z",
  },
  {
    id: 3,
    title: "Fix login flow bug",
    description: "Resolve redirect issue on failed login",
    category: "Bug",
    status: "In Progress",
    priority: "High",
    createdAt: "2024-07-03T09:45:00.000Z",
  },
  {
    id: 4,
    title: "Implement dark mode",
    description: "Add dark theme support",
    category: "Feature",
    status: "To Do",
    priority: "Medium",
    createdAt: "2024-07-04T15:20:00.000Z",
  },
  {
    id: 5,
    title: "Refactor auth module",
    description: "Improve code structure and remove deprecated code",
    category: "Refactor",
    status: "Done",
    priority: "Medium",
    createdAt: "2024-07-05T14:10:00.000Z",
  },
  {
    id: 6,
    title: "Write unit tests for payment module",
    category: "Test",
    status: "In Progress",
    priority: "High",
    createdAt: "2024-07-06T08:05:00.000Z",
  },
  {
    id: 7,
    title: "New Task Fix",
    description: "Test",
    category: "Test",
    status: "In Progress",
    priority: "Low",
    createdAt: "2025-07-18T19:01:40.915Z",
  },
];
